name:  Nowa funkcja
description: Zaproponuj now funkcj.
title: "[Nowa Funkcja]: "
labels: [" Typ: Funkcja"]
assignees:
  - malezjaa
body:
  - type: checkboxes
    attributes:
      label: "Czy istnieje ju偶 dla tej funkcji zgoszenie?"
      description: "Wyszukaj [tutaj](../issues?q=is%3Aissue) czy nie istnieje ju偶 zgoszenie dla tej funkcji."
      options:
        - label: "Przeszukaem istniejce zgoszenia"
          required: true
  - type: textarea
    id: related-to-issue
    attributes:
      label: Czy jest to powizane z innym zgoszeniem?
      description: Czy ta funkcja jest powizane z innym zgoszeniem? Jeli tak, to opisz.
      placeholder: "..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Opisz now funkcj
      description: Opisz now funkcj, kt贸r chciaby zobaczy.
      placeholder: "..."
    validations:
      required: true
  - type: textarea
    id: describe-the-solution
    attributes:
      label: Opisz rozwizanie, kt贸re chciaby zobaczy
      description: Dokadnie opisz rozwizanie, kt贸re chciaby zobaczy.
      placeholder: "..."
    validations:
      required: true
  - type: textarea
    id: describe-alternatives
    attributes:
      label: Opisz alternatywne rozwizania
      description: Opisz alternatywne rozwizania, kt贸re rozwa偶ae.
      placeholder: "..."
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Dodatkowe informacje
      description: Dodaj jakiekolwiek dodatkowe informacje na temat nowej funkcji.
      placeholder: "..."
    validations:
      required: true
